name: Bandit Security Scan

on:
  push:
    paths:
      - '**.py'
      - '.github/workflows/bandit.yml'
  pull_request:

jobs:
  bandit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Bandit
        run: |
          python -m pip install --upgrade pip
          pip install bandit

      - name: Scan with Bandit
        run: bandit -r . -ll