name: Build EXE Windows

on:
  [push]

jobs:
  build-exe:
    runs-on: windows-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Get version from version.py
        id: get_version
        run: |
          $version = (Get-Content version.py | Select-String -Pattern "VERSION\s*=\s*['""](.*?)['""]").Matches.Groups[1].Value
          echo "VERSION=$version" >> $env:GITHUB_ENV
        shell: pwsh

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller

      - name: Build EXE
        run: |
          pyinstaller --onefile --windowed --name BeautyCenter --collect-all PySide6 main.py
          
      - name: Create or Update Latest Release
        uses: softprops/action-gh-release@v2
        with:
          body: |
            Latest development build.
            Version: ${{ env.VERSION }}
            Commit: ${{ github.sha }}
          name: Nightly Build ${{ env.VERSION }}
          tag_name: latest-build
          prerelease: true
          files: |
            dist/BeautyCenter.exe
