name: Build EXE Windows

on:
  [ push ]

env:
  RELEASE_TAG: latest-build

jobs:
  build-exe:
    runs-on: windows-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install UPX
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $release = Invoke-RestMethod -Uri 'https://api.github.com/repos/upx/upx/releases/latest' -Headers @{
            "Authorization" = "Bearer $env:GITHUB_TOKEN"
            "Accept"        = "application/vnd.github+json"
            "User-Agent"    = "GH-Actions-UPX"
          }
          $asset = $release.assets | Where-Object { $_.name -like '*-win64.zip' }
          $downloadUrl = $asset.browser_download_url
          Invoke-WebRequest -Uri $downloadUrl -OutFile 'upx.zip'
          Expand-Archive -Path 'upx.zip' -DestinationPath 'upx_temp'
          $upxExe = (Get-ChildItem -Path 'upx_temp' -Filter 'upx.exe' -Recurse | Select-Object -First 1).FullName
          $upxDir = Split-Path $upxExe -Parent
          echo "$upxDir" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "UPX_PATH=$upxDir" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        shell: pwsh

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install PyInstaller
        run: |
          python -m pip install pyinstaller

      - name: Get name version app from name_version.py
        id: get_version
        run: |
          $nameMatch = Get-Content name_version.py | Select-String -Pattern "APP_NAME\s*=\s*['""](.*?)['""]"
          if ($null -ne $nameMatch) 
          {
            $appName = $nameMatch.Matches.Groups[1].Value
            echo "APP_NAME=$appName" >> $env:GITHUB_ENV
            echo "Found app name: $appName"
          } 
          else 
          {
            echo "::error::APP_NAME not found in name_version.py"
            exit 1
          }
          
          $versionMatch = Get-Content name_version.py | Select-String -Pattern "APP_VERSION\s*=\s*['""](.*?)['""]"
          if ($null -ne $versionMatch) 
          {
            $appVersion = $versionMatch.Matches.Groups[1].Value
            echo "APP_VERSION=$appVersion" >> $env:GITHUB_ENV
            echo "Found version: $appVersion"
          } 
          else 
          {
            echo "::error::APP_VERSION not found in name_version.py"
            exit 1
          }
        shell: pwsh

      - name: Build Windows EXE
        run: ./build_exe_beauty_center.ps1

      - name: Delete previous release and tag (if present)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $headers = @{
            Authorization = "Bearer $env:GITHUB_TOKEN"
            Accept = "application/vnd.github+json"
            "User-Agent" = "gh-actions"
          }
          try
          {
            $release = Invoke-RestMethod -Headers $headers -Uri "https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ env.RELEASE_TAG }}"
          
            if ($release.id) 
            {
              Invoke-RestMethod -Headers $headers -Uri "https://api.github.com/repos/${{ github.repository }}/releases/$($release.id)" -Method DELETE
              Write-Host "Deleted previous release with tag '${{ env.RELEASE_TAG }}'"
            }
          } 
          catch 
          {
            Write-Host "No existing release found"
          }
          try 
          {
            git push origin :refs/tags/${{ env.RELEASE_TAG }}
            Write-Host "Deleted tag '${{ env.RELEASE_TAG }}' on remote (if existed)"
          } 
          catch 
          {
            Write-Host "No tag to delete"
          }
        shell: pwsh

      - name: List dist directory before rename
        run: ls -l dist
        shell: bash

      - name: Create or Update Latest Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          name: ${{ env.APP_NAME }} v. ${{ env.APP_VERSION }}
          body: |
            Latest development build.
            Version: ${{ env.APP_VERSION }}
            Commit: ${{ github.sha }}
          files: |
            dist/${{ env.APP_NAME }} v. ${{ env.APP_VERSION }}.exe
