name: Code Quality (Pylint)

on:
  push:
    paths:
      - '**.py'
      - '.github/workflows/pylint.yml'
      - 'requirements.txt'
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    strategy:
      matrix:
        python-version: [ "3.13" ]

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - uses: actions/checkout@v5

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-pylint-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-pylint-
            ${{ runner.os }}-pip-

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint

      - name: Run Pylint
        run: |
          pylint $(git ls-files '*.py') || exit 0
