name: Tests

on:
  push:
    paths:
      - '**.py'
      - 'requirements.txt'
      - '.github/workflows/pytest.yml'
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}

    permissions:
      contents: read
      pull-requests: write

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ '3.11', '3.12', '3.13' ]

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Qt + OpenGL + system libs for PySide6 (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libegl1 \
            libglib2.0-0 \
            libx11-xcb1 \
            libxkbcommon-x11-0 \
            libxrender1 \
            libsm6 \
            libxext6 \
            libglu1-mesa \
            libopengl0 \
            xvfb

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ matrix.python-version }}-
            ${{ runner.os }}-pip-

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Version & debug info
        run: |
          python --version
          pip show PySide6
          pip list

      - name: Run Pytest (headless)
        run: |
          xvfb-run -a pytest --junitxml=pytest-report.xml --maxfail=1 --disable-warnings --exitfirst || test $? -eq 5
