name: Pytest

on:
  push:
    paths:
      - '**.py'
      - 'requirements.txt'
      - '.github/workflows/pytest.yml'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run Pytest
        run: pytest --maxfail=1 --disable-warnings --exitfirst || test $? -eq 5
